// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int cat_Id { get; set; }
        public string cat_Descripcion { get; set; }
        public int? cat_UsuCrea { get; set; }
        public DateTime? cat_FechaCrea { get; set; }
        public int? cat_UsuModi { get; set; }
        public DateTime? cat_FechaModi { get; set; }
        public bool? cat_Estado { get; set; }

        public virtual tbUsuarios cat_UsuCreaNavigation { get; set; }
        public virtual tbUsuarios cat_UsuModiNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}