// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbVentas = new HashSet<tbVentas>();
        }

        public int cli_ID { get; set; }
        public string cli_Nombre { get; set; }
        public string cli_Apellido { get; set; }
        public string cli_DNI { get; set; }
        public DateTime cli_FechaNacimiento { get; set; }
        public string cli_Sexo { get; set; }
        public string cli_Telefono { get; set; }
        public int cli_Municipio { get; set; }
        public int cli_EstadoCivil { get; set; }
        public int cli_UsuarioCrea { get; set; }
        public DateTime? cli_FechaCrea { get; set; }
        public int? cli_UsuarioModi { get; set; }
        public DateTime? cli_FechaModi { get; set; }
        public bool? cli_Estado { get; set; }

        public virtual tbMunicipios cli_MunicipioNavigation { get; set; }
        public virtual tbUsuarios cli_UsuarioCreaNavigation { get; set; }
        public virtual tbUsuarios cli_UsuarioModiNavigation { get; set; }
        public virtual ICollection<tbVentas> tbVentas { get; set; }
    }
}