// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbMetodoPago
    {
        public tbMetodoPago()
        {
            tbVentas = new HashSet<tbVentas>();
        }

        public int met_Id { get; set; }
        public string met_Descripcion { get; set; }
        public int? met_UsuCrea { get; set; }
        public DateTime? met_FechaCrea { get; set; }
        public int? met_usuModi { get; set; }
        public DateTime? met_FechaModi { get; set; }
        public bool? met_Estado { get; set; }

        public virtual tbUsuarios met_UsuCreaNavigation { get; set; }
        public virtual tbUsuarios met_usuModiNavigation { get; set; }
        public virtual ICollection<tbVentas> tbVentas { get; set; }
    }
}