// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbClientes = new HashSet<tbClientes>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbProveedores = new HashSet<tbProveedores>();
            tbSucursales = new HashSet<tbSucursales>();
        }

        public int mun_ID { get; set; }
        public int mun_depID { get; set; }
        public string mun_Descripcion { get; set; }
        public int mun_UsuarioCrea { get; set; }
        public DateTime? mun_FechaCrea { get; set; }
        public int? mun_UsuarioModi { get; set; }
        public DateTime? mun_FechaModi { get; set; }

        public virtual tbUsuarios mun_UsuarioCreaNavigation { get; set; }
        public virtual tbUsuarios mun_UsuarioModiNavigation { get; set; }
        public virtual tbDepartamentos mun_dep { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbProveedores> tbProveedores { get; set; }
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}