// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbProveedores
    {
        public tbProveedores()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int prv_ID { get; set; }
        public string prv_NombreCompañia { get; set; }
        public string prv_NombreContacto { get; set; }
        public string prv_TelefonoContacto { get; set; }
        public string prv_DireccionEmpresa { get; set; }
        public string prv_DireccionContacto { get; set; }
        public string prv_SexoContacto { get; set; }
        public int prv_UsuarioCrea { get; set; }
        public DateTime? prv_FechaCrea { get; set; }
        public int? prv_UsuarioModi { get; set; }
        public DateTime? prv_FechaModi { get; set; }
        public bool? prv_Estado { get; set; }

        public virtual tbUsuarios prv_UsuarioCreaNavigation { get; set; }
        public virtual tbUsuarios prv_UsuarioModiNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}