// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbSucursales
    {
        public tbSucursales()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbVentas = new HashSet<tbVentas>();
        }

        public int suc_Id { get; set; }
        public string suc_Descripcion { get; set; }
        public int suc_Municipio { get; set; }
        public int? suc_UsuCrea { get; set; }
        public DateTime? suc_FechaCrea { get; set; }
        public int? suc_usuModi { get; set; }
        public DateTime? suc_FechaModi { get; set; }
        public bool? suc_Estado { get; set; }

        public virtual tbMunicipios suc_MunicipioNavigation { get; set; }
        public virtual tbUsuarios suc_UsuCreaNavigation { get; set; }
        public virtual tbUsuarios suc_usuModiNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbVentas> tbVentas { get; set; }
    }
}