// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tb_Municipios_LIST
    {
        public int mun_ID { get; set; }
        public string mun_depID { get; set; }
        public string mun_Descripcion { get; set; }
    }
}