// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbSucursales_DDL
    {
        public int suc_Id { get; set; }
        public string suc_Descripcion { get; set; }
    }
}