// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbClientes_LIST
    {
        public int cli_ID { get; set; }
        public string cli_Nombre { get; set; }
        public string cli_DNI { get; set; }
        public DateTime cli_FechaNacimiento { get; set; }
        public string cli_sexo { get; set; }
        public string cli_Telefono { get; set; }
        public string cli_Municipio { get; set; }
        public string cli_EstadoCivil { get; set; }
    }
}