// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbEmpleados_LIST
    {
        public int emp_ID { get; set; }
        public string emp_Nombre { get; set; }
        public string emp_DNI { get; set; }
        public DateTime emp_FechaNacimiento { get; set; }
        public string emp_Sexo { get; set; }
        public string emp_Telefono { get; set; }
        public string emp_Municipio { get; set; }
        public string emp_Correo { get; set; }
        public string emp_EstadoCivil { get; set; }
        public string emp_Sucursal { get; set; }
    }
}