// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbDepartamentos_DDL
    {
        public int dep_ID { get; set; }
        public string dep_Descripcion { get; set; }
    }
}