// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbClientes_DDL
    {
        public int cli_ID { get; set; }
        public string cli_Nombre { get; set; }
    }
}