// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbEmpleados_DDL
    {
        public int? emp_ID { get; set; }
        public string emp_Nombre { get; set; }
    }
}