// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Gral_tbUsuarios_LIST
    {
        public int usu_ID { get; set; }
        public string usu_Usuario { get; set; }
        public string Empleado { get; set; }
        public bool usu_EsAdmin { get; set; }
    }
}