// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbProductos_LIST
    {
        public string pro_Codigo { get; set; }
        public string pro_Nombre { get; set; }
        public string pro_StockInicial { get; set; }
        public decimal pro_PrecioUnitario { get; set; }
        public string cat_Descripcion { get; set; }
        public string prv_NombreCompañia { get; set; }
        public string pro_Proveedor { get; set; }
    }
}