// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbProveedores_LIST
    {
        public string prv_NombreCompañia { get; set; }
        public string prv_NombreContacto { get; set; }
        public string prv_TelefonoContacto { get; set; }
        public string prv_Municipio { get; set; }
        public string prv_DireccionEmpresa { get; set; }
        public string prv_DireccionContacto { get; set; }
        public string prv_SexoContacto { get; set; }
    }
}