// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbProveedores_DDL
    {
        public int prv_ID { get; set; }
        public string prv_NombreCompañia { get; set; }
    }
}