// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbCategorias_DDL
    {
        public int cat_Id { get; set; }
        public string cat_Descripcion { get; set; }
    }
}