// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbVentasDetalle_LIST
    {
        public int vde_Id { get; set; }
        public int vde_VentaId { get; set; }
        public string vde_Producto { get; set; }
        public int vde_Cantidad { get; set; }
    }
}