// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbMetodoPago_LIST
    {
        public int met_Id { get; set; }
        public string met_Descripcion { get; set; }
    }
}