// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbVentas_LIST
    {
        public int ven_Id { get; set; }
        public string ven_Cliente { get; set; }
        public string ven_Empleado { get; set; }
        public DateTime? ven_Fecha { get; set; }
        public string suc_Descripcion { get; set; }
        public string met_Descripcion { get; set; }
    }
}