// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class Vw_Maqui_tbInventario_LIST
    {
        public int inv_Id { get; set; }
        public string pro_Nombre { get; set; }
        public string pro_StockInicial { get; set; }
        public int inv_Cantidad { get; set; }
    }
}