// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_tbVentasDetalles_List
    {
        public int vde_Id { get; set; }
        public int vde_VentaId { get; set; }
        public int pro_Id { get; set; }
        public string pro_Nombre { get; set; }
        public int? pro_Categoria { get; set; }
        public int vde_Cantidad { get; set; }
        public decimal pro_PrecioUnitario { get; set; }
        public decimal? vde_PrecioTotal { get; set; }
    }
}