// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_tbVentas_List
    {
        public int ven_Id { get; set; }
        public string cli_Nombres { get; set; }
        public string emp_Nombres { get; set; }
        public string met_Descripcion { get; set; }
        public DateTime? ven_Fecha { get; set; }
    }
}