// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Maquillaje.DataAccess.Context;

namespace Maquillaje.DataAccess.Context
{
    public partial class TiendamaquillajeContext
    {

        [DbFunction("UDF_Gral_tbClienteInfo_DDL", "dbo")]
        public IQueryable<UDF_Gral_tbClienteInfo_DDLResult> UDF_Gral_tbClienteInfo_DDL(int? id)
        {
            return FromExpression(() => UDF_Gral_tbClienteInfo_DDL(id));
        }

        [DbFunction("UDF_Gral_tbMunicipio_DDL", "dbo")]
        public IQueryable<UDF_Gral_tbMunicipio_DDLResult> UDF_Gral_tbMunicipio_DDL(int? depto)
        {
            return FromExpression(() => UDF_Gral_tbMunicipio_DDL(depto));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UDF_Gral_tbClienteInfo_DDLResult>().HasNoKey();
            modelBuilder.Entity<UDF_Gral_tbMunicipio_DDLResult>().HasNoKey();
        }
    }
}
