// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_Gral_tbClientes_DDLResult
    {
        public int cli_ID { get; set; }
        public string cli_Nombre { get; set; }
    }
}
