// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_tbVentas_ListarDetallesPorIdVentaResult
    {
        public int vde_Id { get; set; }
        public int vde_VentaId { get; set; }
        public string pro_Codigo { get; set; }
        public string pro_Nombre { get; set; }
        public int vde_Cantidad { get; set; }
        public decimal pro_PrecioUnitario { get; set; }
        public decimal? MontoTotal { get; set; }
    }
}
