// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_Maqui_tbProductos_DDLResult
    {
        public int pro_Id { get; set; }
        public string pro_Nombre { get; set; }
    }
}
