// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_tbProductos_CargarStockProductoPorIdResult
    {
        public int inv_Cantidad { get; set; }
    }
}
