// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_tbProductos_ListarProductoPorIdResult
    {
        public int pro_Id { get; set; }
        public string pro_Codigo { get; set; }
        public string pro_Nombre { get; set; }
        public int? pro_Categoria { get; set; }
        public int? pro_Proveedor { get; set; }
        public int inv_Cantidad { get; set; }
        public decimal pro_PrecioUnitario { get; set; }
    }
}
