// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_Gral_tbSucursales_DDLResult
    {
        public int suc_Municipio { get; set; }
        public int dep_ID { get; set; }
    }
}
