// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_tbCategorias_BuscarCategoriasResult
    {
        public int cat_Id { get; set; }
        public string cat_Descripcion { get; set; }
        public string cat_UsuCrea { get; set; }
        public string cat_UsuModi { get; set; }
        public DateTime? cat_FechaCrea { get; set; }
        public DateTime? cat_FechaModi { get; set; }
    }
}
