// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDF_Gral_tbMunicipio_DDLResult
    {
        public int mun_ID { get; set; }
        public string mun_Descripcion { get; set; }
    }
}
